version: '3'

services:
  discord-time-tracker:
    build:
      context: .
      dockerfile: Dockerfile
    # restart: always
    ports:
      - 8033:8080
    volumes:
      - ./data:/var/lib:rw
      - ./log:/var/log:rw
    network_mode: bridge
